$$$$$$"WORK HARD IN SILENCE LET YOUR SUCCESS BE YOUR NOICE"$$$$$$
________________THIS IS MY ALLTIME FAVOURITE QUOTE_______________
SO I WILL FOLLOW MY OWN PATH WITH THE SUPPORT OF LORD VEKATESWARA
SUCCESSFULLY COMPLETED MY ANSIBLE JOB TO RUN AS CI/CD IN  JENKINS
SUCCESSFULLY I HAVE COMPLETED MY CI/CD BY USING THE TOMCAT SERVER
